import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import { Toaster } from 'sonner'
import '../globals.css'
import Providers from './Providers'

const DM_SANS_FONT = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ermirblushaj',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale} className='bg-custom-navy'>
      <body id='body' className={`${DM_SANS_FONT.className}`}>
        <Toaster position='bottom-right' richColors />
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  )
}
